### ISSUE TITLE
Question about useage

### ISSUE THREAD

**Issue by MostHated** [tomtc123/Unity-Jenkins#1]
Hey there,
    Forgive my ignorance. I know a lot of web developers and such use Jenkins but I am not super familiar with it, what are advantages of using it along with Unity?

Thanks,
-MH

**Comment by tomtc123** [comment]
Hi~
Jenkins convenient tester build Android or iOS package without program environment(Unity3d,JDK,NDK) since everything prepare on build server machine.Forgive my poor English.

**Comment by MostHated** [comment]
I think I understand what you mean, you are saying I would not have to use the PC that I am working on in order to create a build for mobile devices? Do you just put the files on a server and it will do the build for you? Does that work for builds for Windows as well? This sounds great.

**Comment by tomtc123** [comment]
Yes, I put all the files on my server, and works for Windows

**Comment by MostHated** [comment]
This is great news, and definitely a productivity booster if you have your own server as the machine you are using no longer has to sit there and wait for the building to occur, especially if you plan to do mobile and windows builds. I will definitely be trying this out. Thanks!
